image: Ubuntu1804  # образ для сборки

stack: node 12  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

environment:
  access_token:
    secure: OZg9+VKt3YNP7o50iMe8UYIUu6xmFZtQtcYvaOm08FCzn4OlVRk8ARQXDk8RxJXU

install:
  - yarn  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn build   # команда сборки

test_script:
  - yarn lint && yarn test  # скрипт тестирования

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name Nikiteo
  - git config --global user.email zhigiley.nikita2012@yandex.ru
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
